[project]
name = "elgatron3000"
description = "Elgatron3000 is an epic Discord bot designed to provide some fun and useful features to our server :)"
version = "0.11.2"

license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
readme = "README.md"

requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.3",
    "discord-py>=2.7.1",
    "epicstore-api>=0.2.0",
    "numpy>=2.4.6",
    "pillow>=12.3.0",
    "pyboy>=2.7.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.21",
    "tortoise-orm>=1.1.7",
    "ty>=0.0.58",
]

[project.urls]
"Homepage" = "https://github.com/Krissibro/Elgatron3000"

[tool.uv]
package = true

[tool.ty.environment]
python = ".venv"
python-version = "3.12"
root = ["."]


[project.scripts]
elgatron = "main:main"
